#official nodejs image
FROM  node:22-alpine3.18

#set working directory
WORKDIR /usr/src

COPY package*.json ./

#install all dependencies
RUN npm install --force

#Copy rest of application code into container
COPY ..

#command to run application
CMD ['npm', 'start']